INPUT:
  FRAMES: 5
  HEIGHT: 2168
  WIDTH: 3848
  SAMPLES: -1
TRAIN:
  ITERS: [16000, 120000]
  BATCH: [6, 3]
  LR: 0.001
  CLIP_GRADS: True
MOTION:
  STACK_FRAMES: True
  TRAIN:
    DELTA: [0.01, 0.01, 0.05, 0.005, 0.02, 0.005]
STRUCTURE:
  MODE: concat
  HG_COUNT: 2